### ISSUE TITLE
Error running `scripts/genContract.ts`

### ISSUE THREAD

**Issue by critesjosh** [noir-lang/noir-starter#2]
When I try to generate the contract using the node script I get the following error. Is this a problem with the `@noir-lang` dependency versions?

```
  noir-starter-template git:(main) ✗ ts-node scripts/genContract.ts 
/home/josh/Documents/GitHub/noir-starter-template/node_modules/@noir-lang/noir-source-resolver/lib/index.js:2
export let read_file = function (source_id) {
^^^^^^

SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1149:20)
    at Module._compile (node:internal/modules/cjs/loader:1190:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Object.require.extensions.<computed> [as .js] (/home/josh/.nvm/versions/node/v18.14.0/lib/node_modules/ts-node/src/index.ts:1608:43)
...
```

**Comment by critesjosh** [comment]
Downgrading to `"@noir-lang/noir-source-resolver": "1.1.1",` fixes this, but then I get

```
noir-starter-template git:(main) ✗ ts-node scripts/genContract.ts
RuntimeError: unreachable
    at wasm://wasm/013555e2:wasm-function[518]:0x7a193
    at wasm://wasm/013555e2:wasm-function[553]:0x7b8d0
    at wasm://wasm/013555e2:wasm-function[756]:0x7fd2c
    at wasm://wasm/013555e2:wasm-function[662]:0x7e67b
    at wasm://wasm/013555e2:wasm-function[721]:0x7f683
    at wasm://wasm/013555e2:wasm-function[572]:0x7c35b
    at wasm://wasm/013555e2:wasm-function[129]:0x4cdf4
    at wasm://wasm/013555e2:wasm-function[591]:0x7cb5b
    at module.exports.serialise_acir_to_barrtenberg_circuit (/home/josh/Documents/GitHub/noir-starter-template/node_modules/@noir-lang/aztec_backend/aztec_backend.js:308:14)
    at setup_generic_prover_and_verifier (/home/josh/Documents/GitHub/noir-starter-template/node_modules/@noir-lang/barretenberg/dest/client_proofs/generic_proof/index.js:27:86)
```

**Comment by critesjosh** [comment]
@signorecello I notice that in `package.json` there are `^` in front of some package version numbers that probably shouldn't have them since we need version numbers to match exactly

`"@noir-lang/noir-source-resolver": "^1.1.0",`
`"@noir-lang/noir_wasm": "^0.3.2-bcdfd526",`
`"@noir-lang/aztec_backend": "^0.1.0-0c3b2f2",`

when i try to install `@noir-lang/aztec_backend@0.1.0-0c3b2f2` as specified on [this](https://noir-lang.org/typescript) page of the docs i get 

![image](https://user-images.githubusercontent.com/18372439/234985887-6020511c-bd06-431b-a2dc-93decde9f875.png)

**Comment by critesjosh** [comment]
I was getting the above errors when installing with yarn. Weird that this works when installing via npm even though when using yarn i am using pinned versions.

**Comment by signorecello** [comment]
works now with the stable npm releases
