### ISSUE TITLE
starter app not working

### ISSUE THREAD

**Issue by wighawag** [noir-lang/noir-starter#81]
### Aim

Wanted to get running with the starter template

### Expected Behavior

Expected the starter template to work

On that note, it would far better if the template was minimal and did not choose to use a framework like react and extra dependencies

### Bug

Getting these error when navigating to http://localhost:5173/
```

￼wagmi.js?v=4eab65be:4634 Uncaught 
Error: No QueryClient set, use QueryClientProvider to set one
    at useQueryClient (￼wagmi.js?v=4eab65be:4634:11)
    at useMutation (￼wagmi.js?v=4eab65be:4784:18)
    at useConnect (￼wagmi.js?v=4eab65be:6138:46)
    at useOnChainVerification (￼useOnChainVerification.tsx:9:35)
    at Component (￼index.tsx:12:3)
    at renderWithHooks (￼react-dom_client.js?v=2ffc14ff:12171:26)
    at mountIndeterminateComponent (￼react-dom_client.js?v=2ffc14ff:14921:21)
    at beginWork (￼react-dom_client.js?v=2ffc14ff:15902:22)
    at HTMLUnknownElement.callCallback2 (￼react-dom_client.js?v=2ffc14ff:3674:22)
    at Object.invokeGuardedCallbackDev (￼react-dom_client.js?v=2ffc14ff:3699:24)
￼react-dom_client.js?v=2ffc14ff:14036 The above error occurred in the <Component> component:

    at Component (￼http://localhost:5173/components/index.tsx:18:31)
    at div
    at InitWasm (￼http://localhost:5173/index.tsx:21:21)
    at Hydrate (￼http://localhost:5173/node_modules/.vite/deps/wagmi.js?v=4eab65be:3493:11)
    at WagmiProvider (￼http://localhost:5173/node_modules/.vite/deps/wagmi.js?v=4eab65be:3517:11)
    at Providers (￼http://localhost:5173/index.tsx:43:29)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit ￼https://reactjs.org/link/error-boundaries to learn more about error boundaries.
￼react-dom_client.js?v=2ffc14ff:19409 Uncaught 
Error: No QueryClient set, use QueryClientProvider to set one
    at useQueryClient (￼wagmi.js?v=4eab65be:4634:11)
    at useMutation (￼wagmi.js?v=4eab65be:4784:18)
    at useConnect (￼wagmi.js?v=4eab65be:6138:46)
    at useOnChainVerification (￼useOnChainVerification.tsx:9:35)
    at Component (￼index.tsx:12:3)
    at renderWithHooks (￼react-dom_client.js?v=2ffc14ff:12171:26)
    at mountIndeterminateComponent (￼react-dom_client.js?v=2ffc14ff:14921:21)
    at beginWork (￼react-dom_client.js?v=2ffc14ff:15902:22)
    at beginWork$1 (￼react-dom_client.js?v=2ffc14ff:19749:22)
    at performUnitOfWork (￼react-dom_client.js?v=2ffc14ff:19194:20)
```

### To Reproduce

1.
2.
3.
4.

### Would you like to submit a PR for this Issue?

No

**Comment by critesjosh** [comment]
@signorecello have you seen this one before?

**Comment by signorecello** [comment]
I haven't, wondering what's your viem version in this project @wighawag ?

**Comment by wighawag** [comment]
@signorecello I am using the yarn.lock version

I am basically doing this:

```
npm create noir # chose "Browser App using Vite"
cd my-noir-app
yarn
yarn dev
```

**Comment by signorecello** [comment]
Yes I can reproduce, will push a fixed version today. I may add a frontend test to the test suite just to be sure it's consistently passing
